detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  FeatureEnvy:
    enabled: false

  UtilityFunction:
    enabled: false
    public_methods_only: true
